name: Gest
favicon: null
layout_spectrum: 0.9769387752749026
typography_spectrum: 0.5829213494434953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
